name: Auto Update top30_foreign_trade_v2

on:
  schedule:
    - cron: '0,15,30,45 7-10 * * 1-5'
    - cron: '0 11 * * 1-5'
    - cron: '0,15,30,45 21-23 * * 0-4'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run script
      run: |
        python scripts/twse_top30_v2_2.py

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "auto update dashboard" || echo "no changes"
        git push
